behaviors:
  TicTacToe:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 100
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 20000
      team_change: 80000
      swap_steps: 10000
      window: 5
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
